# Generated by Django 4.2.28 on 2026-02-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='subscription_plan',
            new_name='service_plan',
        ),
    ]
