# Generated by Django 4.2.28 on 2026-02-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_subscription_plan_tenant_service_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The tenant this user belongs to. NULL for platform-level superusers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="users.tenant",
            ),
        ),
    ]
