# Generated by Django 4.2.23 on 2026-02-11 17:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wallettransaction_address'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_pickup_time', models.TimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery Assignment',
                'verbose_name_plural': 'Delivery Assignments',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('delivery_confirmation', 'Delivery Confirmation'), ('delivery_reminder', 'Delivery Reminder'), ('delivery_update', 'Delivery Update'), ('delivery_completion', 'Delivery Completion')], max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_to', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Delivery Notification',
                'verbose_name_plural': 'Delivery Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_deliveries', models.IntegerField(default=50, help_text='Maximum number of deliveries for this time slot')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('actual_delivery_time', models.TimeField(blank=True, null=True)),
                ('driver_notes', models.TextField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('payment_processed', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.address')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_statuses', to='main.subscription')),
            ],
            options={
                'verbose_name': 'Delivery Status',
                'verbose_name_plural': 'Delivery Statuses',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('subscription', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['zone__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_delivery_time', models.IntegerField(default=30, help_text='Estimated delivery time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.AddField(
            model_name='route',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='driver.zone'),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='driver.zone'),
        ),
        migrations.AddField(
            model_name='deliverynotification',
            name='delivery_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='driver.deliverystatus'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='driver.deliverystatus'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.deliverydriver'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('name', 'zone')},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryschedule',
            unique_together={('zone', 'day_of_week', 'start_time')},
        ),
    ]
