# Generated by Django 4.2.28 on 2026-02-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0002_deliveryassignment_deliverydriver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydriver",
            name="routes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific routes this driver is assigned to",
                related_name="assigned_drivers",
                to="driver.route",
            ),
        ),
        migrations.AddField(
            model_name="deliverydriver",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                help_text="Zones this driver is assigned to cover",
                related_name="assigned_drivers",
                to="driver.zone",
            ),
        ),
    ]
