# Generated by Django 4.2.28 on 2026-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="unitofmeasure",
            options={"ordering": ["category", "name"]},
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="tenant",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="cost_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="supplier",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="tenant_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="References Tenant.id in the shared database (not a FK due to multi-DB)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="category",
            field=models.CharField(
                choices=[
                    ("weight", "Weight"),
                    ("volume", "Volume"),
                    ("unit", "Unit/Piece"),
                    ("length", "Length"),
                ],
                max_length=20,
            ),
        ),
    ]
