# Generated by Django 4.2.28 on 2026-02-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_subscription_plan_tenant_service_plan'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionPlan',
            new_name='ServicePlan',
        ),
    ]
