# Generated by Django 4.2.28 on 2026-02-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rename_subscriptionplan_serviceplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceplan',
            name='max_orders_per_month',
        ),
    ]
