# Generated by Django 4.2.28 on 2026-02-12 07:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_subscription_plan_tenant_service_plan"),
        ("organizations", "0003_remove_serviceplan_max_orders_per_month"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceplan",
            options={"ordering": ["price_monthly"]},
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional feature flags as JSON, e.g. {'custom_branding': true}",
            ),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="has_analytics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="has_customer_app",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="has_delivery_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="has_multi_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="has_whatsapp_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="max_customers",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="max_menu_items",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="max_orders_per_month",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="max_staff_users",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="price_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Monthly subscription price for the tenant",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="price_yearly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Yearly subscription price (discounted)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free / Trial"),
                    ("basic", "Basic"),
                    ("pro", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="trial_days",
            field=models.PositiveIntegerField(
                default=14, help_text="Number of free trial days for new tenants"
            ),
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("current_period_start", models.DateField()),
                ("current_period_end", models.DateField()),
                ("trial_end", models.DateField(blank=True, null=True)),
                ("next_invoice_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_subscriptions",
                        to="organizations.serviceplan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("due_date", models.DateField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="organizations.tenantsubscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saas_invoices",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(help_text="First day of the month")),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("customer_count", models.PositiveIntegerField(default=0)),
                ("staff_count", models.PositiveIntegerField(default=0)),
                ("menu_item_count", models.PositiveIntegerField(default=0)),
                ("subscription_count", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
                "unique_together": {("tenant", "period")},
            },
        ),
    ]
