# Generated by Django 4.2.28 on 2026-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0004_alter_serviceplan_options_serviceplan_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceplan",
            name="max_customers",
            field=models.PositiveIntegerField(
                default=1000,
                help_text="Max registered B2C customers / subscribers (0 = unlimited)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="max_menu_items",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Max menu items the kitchen can create (0 = unlimited)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="max_orders_per_month",
            field=models.PositiveIntegerField(
                default=50000, help_text="Max meal deliveries per month (0 = unlimited)"
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="max_staff_users",
            field=models.PositiveIntegerField(
                default=15, help_text="Max kitchen/admin staff accounts (0 = unlimited)"
            ),
        ),
    ]
