import 'package:flutter/material.dart';
import '../../domain/food_item.dart';

class AddItemModal extends StatefulWidget {
  final Function(FoodItem) onSave;

  const AddItemModal({super.key, required this.onSave});

  @override
  State<AddItemModal> createState() => _AddItemModalState();
}

class _AddItemModalState extends State<AddItemModal> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _priceController = TextEditingController();
  final _caloriesController = TextEditingController();
  
  // Mock Allergens
  final List<String> _availableAllergens = ['Gluten', 'Dairy', 'Nuts', 'Soy', 'Eggs'];
  final List<String> _selectedAllergens = [];
  
  // Mock Inventory Items
  final List<Map<String, String>> _inventoryItems = [
    {'id': 'inv_1', 'name': 'Burger Bun'},
    {'id': 'inv_2', 'name': 'Beef Patty'},
    {'id': 'inv_3', 'name': 'Lettuce'},
  ];
  String? _selectedInventoryItem;

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _priceController.dispose();
    _caloriesController.dispose();
    super.dispose();
  }

  void _saveItem() {
    if (_formKey.currentState!.validate()) {
      final newItem = FoodItem(
        id: '', // Generated by Repo
        name: _nameController.text,
        description: _descriptionController.text,
        basePrice: double.parse(_priceController.text),
        calories: int.parse(_caloriesController.text),
        allergens: _selectedAllergens,
        isActive: true,
        inventoryItemId: _selectedInventoryItem,
      );
      widget.onSave(newItem);
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        child: Container(
          width: 600,
          padding: const EdgeInsets.all(24),
          child: SingleChildScrollView(
            child: Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Add New Food Item',
                    style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 24),
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: _nameController,
                          decoration: const InputDecoration(labelText: 'Name', border: OutlineInputBorder()),
                          validator: (value) => value == null || value.isEmpty ? 'Required' : null,
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: TextFormField(
                          controller: _priceController,
                          decoration: const InputDecoration(labelText: 'Base Price', prefixText: '\$', border: OutlineInputBorder()),
                          keyboardType: const TextInputType.numberWithOptions(decimal: true),
                          validator: (value) => value == null || double.tryParse(value) == null ? 'Invalid Price' : null,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _descriptionController,
                    decoration: const InputDecoration(labelText: 'Description', border: OutlineInputBorder()),
                    maxLines: 3,
                    validator: (value) => value == null || value.isEmpty ? 'Required' : null,
                  ),
                  const SizedBox(height: 16),
                  Row(
                    children: [
                       Expanded(
                        child: TextFormField(
                          controller: _caloriesController,
                          decoration: const InputDecoration(labelText: 'Calories', border: OutlineInputBorder()),
                          keyboardType: TextInputType.number,
                          validator: (value) => value == null || int.tryParse(value) == null ? 'Invalid Calories' : null,
                        ),
                      ),
                       const SizedBox(width: 16),
                       Expanded(
                         child: DropdownButtonFormField<String>(
                           decoration: const InputDecoration(labelText: 'Link Inventory Item', border: OutlineInputBorder()),
                           initialValue: _selectedInventoryItem,
                           items: _inventoryItems.map((item) {
                             return DropdownMenuItem(value: item['id'], child: Text(item['name']!));
                           }).toList(),
                           onChanged: (val) => setState(() => _selectedInventoryItem = val),
                         ),
                       ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  Text('Allergens', style: Theme.of(context).textTheme.titleSmall),
                  const SizedBox(height: 8),
                  Wrap(
                    spacing: 8,
                    children: _availableAllergens.map((allergen) {
                      final isSelected = _selectedAllergens.contains(allergen);
                      return FilterChip(
                        label: Text(allergen),
                        selected: isSelected,
                        onSelected: (selected) {
                          setState(() {
                            if (selected) {
                              _selectedAllergens.add(allergen);
                            } else {
                              _selectedAllergens.remove(allergen);
                            }
                          });
                        },
                      );
                    }).toList(),
                  ),
                  const SizedBox(height: 32),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      TextButton(onPressed: () => Navigator.of(context).pop(), child: const Text('Cancel')),
                      const SizedBox(width: 16),
                      ElevatedButton(onPressed: _saveItem, child: const Text('Save Item')),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      );
  }
}
