# Generated by Django 4.2.23 on 2026-02-11 17:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_customerprofile_notification_remove_customer_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('meal_selection', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Registration Request',
                'verbose_name_plural': 'Customer Registration Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kitchen_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_changes', models.JSONField(help_text='JSON object detailing the requested changes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date', '-end_date'], 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost_per_meal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dietary_preferences',
            field=models.CharField(blank=True, help_text="e.g., 'Gluten-free', 'Vegan'", max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dinner_address',
            field=models.ForeignKey(blank=True, help_text='Optional: specific address for dinner deliveries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_subscriptions', to='main.address'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lunch_address',
            field=models.ForeignKey(blank=True, help_text='Optional: specific address for lunch deliveries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_subscriptions', to='main.address'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_mode',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('card', 'Card'), ('cash', 'Cash')], default='wallet', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='selected_days',
            field=models.JSONField(default=list, help_text='Select the days for delivery'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='want_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='The main time slot for deliveries (e.g., Lunch, Dinner).', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.timeslot'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerprofile'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(default='Transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subscription'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='main_subscr_custome_e3f7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['start_date', 'end_date'], name='main_subscr_start_d_1fc1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'start_date'], name='main_subscr_custome_883030_idx'),
        ),
        migrations.AddField(
            model_name='subscriptioneditrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerprofile'),
        ),
        migrations.AddField(
            model_name='subscriptioneditrequest',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscription'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(related_name='menus', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kitchenprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerprofile'),
        ),
        migrations.AddField(
            model_name='customerregistrationrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='menus',
            field=models.ManyToManyField(help_text='Select the menus included in this subscription.', to='main.menu', verbose_name='Menu Plans'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.invoice'),
        ),
    ]
