# Generated by Django 4.2.28 on 2026-02-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_inventoryitem_options_and_more"),
        ("main", "0004_customerregistrationrequest_invoice_invoiceitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="tenant",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="tenant_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="References Tenant.id in the shared database (not a FK due to multi-DB)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="allergens",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of allergens, e.g. ['Gluten', 'Dairy']",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="calories",
            field=models.PositiveIntegerField(
                default=0, help_text="Calorie count per serving"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to an inventory item for stock tracking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="inventory.inventoryitem",
            ),
        ),
    ]
