# Generated by Django 4.2.28 on 2026-02-12 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_alter_menuitem_options_remove_customerprofile_tenant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for kitchen staff"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_daily_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Menu",
                "verbose_name_plural": "Daily Menus",
                "ordering": ["menu_date", "meal_slot__sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MealSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Lunch, Dinner, Breakfast", max_length=50
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="URL-safe identifier, e.g. lunch, dinner",
                        max_length=30,
                    ),
                ),
                (
                    "cutoff_time",
                    models.TimeField(
                        blank=True,
                        help_text="Orders/changes for this slot must be placed before this time",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use the master item's base price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "portion_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Regular, Family Pack, Diet Portion",
                        max_length=50,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="main.dailymenu",
                    ),
                ),
                (
                    "master_item",
                    models.ForeignKey(
                        help_text="The reusable menu item from the master library",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_appearances",
                        to="main.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Menu Item",
                "verbose_name_plural": "Daily Menu Items",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="meal_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_menus",
                to="main.mealslot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymenu",
            unique_together={("menu_date", "meal_slot")},
        ),
    ]
