# Generated by Django 4.2.28 on 2026-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_daily_menu_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tenant-defined package tier name", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Details about what is included in this package",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Package price in the tenant's currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Currency code (tenant sets their own, e.g. AED, USD, INR)",
                        max_length=10,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("nonveg", "Non-Vegetarian"),
                            ("both", "Both"),
                        ],
                        db_index=True,
                        default="both",
                        help_text="Which diet track this package covers",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="monthly",
                        help_text="Billing cycle for this package",
                        max_length=10,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days in this package cycle"
                    ),
                ),
                (
                    "meals_per_day",
                    models.PositiveIntegerField(
                        default=2, help_text="Number of meal slots included per day"
                    ),
                ),
                (
                    "portion_label",
                    models.CharField(
                        blank=True,
                        help_text="Portion descriptor shown to customers",
                        max_length=50,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Meal Package",
                "verbose_name_plural": "Meal Packages",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="dailymenu",
            options={
                "ordering": ["menu_date", "meal_slot__sort_order", "diet_type"],
                "verbose_name": "Daily Menu",
                "verbose_name_plural": "Daily Menus",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailymenu",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="diet_type",
            field=models.CharField(
                choices=[("veg", "Vegetarian"), ("nonveg", "Non-Vegetarian")],
                db_index=True,
                default="nonveg",
                help_text="Whether this is the Veg or Non-Veg menu for the slot",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="diet_type",
            field=models.CharField(
                choices=[
                    ("veg", "Vegetarian"),
                    ("nonveg", "Non-Vegetarian"),
                    ("both", "Both / Neutral"),
                ],
                db_index=True,
                default="both",
                help_text="Classify as Veg, Non-Veg, or Both (neutral items served on either track)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dailymenuitem",
            name="portion_label",
            field=models.CharField(
                blank=True,
                help_text="Tenant-defined portion descriptor for this item",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mealslot",
            name="code",
            field=models.SlugField(
                help_text="URL-safe identifier for this meal slot", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="mealslot",
            name="name",
            field=models.CharField(
                help_text="Tenant-defined meal slot name", max_length=50
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymenu",
            unique_together={("menu_date", "meal_slot", "diet_type")},
        ),
    ]
