# Generated by Django 4.2.28 on 2026-02-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_add_diet_type_and_meal_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailymenu",
            name="created_by",
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="created_by_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="ID of the user who created this menu", null=True
            ),
        ),
    ]
