# Generated by Django 4.2.28 on 2026-02-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_fix_created_by_cross_db"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailymenu",
            name="created_by_id",
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_daily_menus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
