# Generated by Django 4.2.28 on 2026-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_revert_created_by_to_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="diet_type",
            field=models.CharField(
                choices=[("veg", "Vegetarian"), ("nonveg", "Non-Vegetarian")],
                db_index=True,
                default="nonveg",
                help_text="Whether this subscription is for Vegetarian or Non-Vegetarian meals",
                max_length=10,
            ),
        ),
    ]
