# Generated by Django 4.2.28 on 2026-02-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_subscription_diet_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="The meal slot for deliveries (e.g., Lunch, Dinner).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="main.mealslot",
            ),
        ),
    ]
