# Generated by Django 4.2.28 on 2026-02-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_subscription_use_mealslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealpackage",
            name="menus",
            field=models.ManyToManyField(
                blank=True,
                help_text="Menu plans included in this package",
                related_name="meal_packages",
                to="main.menu",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="meal_package",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected package; menus/diet/cost derived from package",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="main.mealpackage",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="menus",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the menus included in this subscription (or from meal_package).",
                to="main.menu",
                verbose_name="Menu Plans",
            ),
        ),
    ]
