# Generated by Django 4.2.28 on 2026-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_mealpackage_menus_subscription_meal_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, default="", max_length=50, unique=True),
        ),
    ]
