# Generated by Django 4.2.28 on 2026-02-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0003_add_zones_routes_to_deliverydriver"),
        ("main", "0013_invoice_number_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Delivery zone for this address",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="driver.zone",
            ),
        ),
    ]
