# Generated by Django 4.2.28 on 2026-02-13 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("driver", "0003_add_zones_routes_to_deliverydriver"),
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="driver_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy: Use driver field instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned delivery driver",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="driver.deliverydriver",
            ),
        ),
    ]
